server:
  port: 8083
spring:
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 172.16.209.128:9300

  jackson:
        default-property-inclusion: non_null # 配置json处理时忽略空值

  rabbitmq:
    host: 127.0.0.1
    #virtual-host: /leyou
    username: guest
    password: guest


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
feign:
  hystrix:
    enabled: true
ribbon:
  eureka:
    enabled: true
  ReadTimeout: 6000000
  ConnectTimeout: 6000000
hystrix:
  command:
    default:
      execution:
        timeout: enabled=false
        isolation:
          thread:
            timeoutInMilliseconds: 6000000

