server:
  port: 8084
spring:
  application:
    name: goods-web
  thymeleaf:
    cache: false

  spring:
    rabbitmq:
      host: 127.0.0.1
      username: guest
      password: guest

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期

#forword error1
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
#forword error2
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeout-in-milliseconds: 60000