server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 127.0.0.1
    username: guest
    password: guest
    port: 5672

leyou:
  sms:
    accessKeyId: WXMHHH
    accessKeySecret: wxm131411
    singName: 乐优商城
    verifyCodeTemplate: SMS_15991986680

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15